import 'package:flutter/material.dart';
import 'package:flutterapp/hotelapp/generatedcompanydashboardwidget/generated/GeneratedEllipse6Widget.dart';
import 'package:flutterapp/hotelapp/generatedcompanydashboardwidget/generated/GeneratedAdsWidget.dart';
import 'package:flutterapp/hotelapp/generatedcompanydashboardwidget/generated/GeneratedGroup86Widget.dart';
import 'package:flutterapp/hotelapp/generatedcompanydashboardwidget/generated/GeneratedRectangle10Widget.dart';
import 'package:flutterapp/hotelapp/generatedcompanydashboardwidget/generated/GeneratedEllipse5Widget.dart';
import 'package:flutterapp/hotelapp/generatedcompanydashboardwidget/generated/GeneratedRectangle9Widget.dart';
import 'package:flutterapp/hotelapp/generatedcompanydashboardwidget/generated/GeneratedEllipse8Widget.dart';
import 'package:flutterapp/hotelapp/generatedcompanydashboardwidget/generated/GeneratedOrdersWidget.dart';
import 'package:flutterapp/hotelapp/generatedcompanydashboardwidget/generated/GeneratedServicesWidget.dart';
import 'package:flutterapp/hotelapp/generatedcompanydashboardwidget/generated/GeneratedEmployeeWidget.dart';
import 'package:flutterapp/hotelapp/generatedcompanydashboardwidget/generated/GeneratedEllipse7Widget.dart';

/* Frame Company Dashboard
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedCompanyDashboardWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: LayoutBuilder(
          builder: (BuildContext context, BoxConstraints constraints) {
        return SingleChildScrollView(
          scrollDirection: Axis.vertical,
          child: Container(
              height: 926.0,
              child: Stack(children: [
                Container(
                    width: constraints.maxWidth,
                    child: Container(
                      width: 428.0,
                      height: 926.0,
                      child: Stack(
                          fit: StackFit.expand,
                          alignment: Alignment.center,
                          overflow: Overflow.visible,
                          children: [
                            ClipRRect(
                              borderRadius: BorderRadius.zero,
                              child: Container(
                                color: Color.fromARGB(255, 255, 255, 255),
                              ),
                            ),
                            Positioned(
                              left: 339.0,
                              top: 843.0,
                              right: null,
                              bottom: null,
                              width: 71.0,
                              height: 68.0,
                              child: GeneratedGroup86Widget(),
                            ),
                            Positioned(
                              left: 0.0,
                              top: 0.0,
                              right: null,
                              bottom: null,
                              width: 428.0,
                              height: 200.0,
                              child: GeneratedRectangle9Widget(),
                            ),
                            Positioned(
                              left: 0.0,
                              top: 117.0,
                              right: null,
                              bottom: null,
                              width: 428.0,
                              height: 278.0,
                              child: GeneratedRectangle10Widget(),
                            ),
                            Positioned(
                              left: 17.0,
                              top: 140.0,
                              right: null,
                              bottom: null,
                              width: 80.0,
                              height: 80.0,
                              child: GeneratedEllipse5Widget(),
                            ),
                            Positioned(
                              left: 330.0,
                              top: 140.0,
                              right: null,
                              bottom: null,
                              width: 80.0,
                              height: 80.0,
                              child: GeneratedEllipse6Widget(),
                            ),
                            Positioned(
                              left: 229.0,
                              top: 140.0,
                              right: null,
                              bottom: null,
                              width: 80.0,
                              height: 80.0,
                              child: GeneratedEllipse7Widget(),
                            ),
                            Positioned(
                              left: 127.0,
                              top: 140.0,
                              right: null,
                              bottom: null,
                              width: 80.0,
                              height: 80.0,
                              child: GeneratedEllipse8Widget(),
                            ),
                            Positioned(
                              left: 171.0,
                              top: 34.0,
                              right: null,
                              bottom: null,
                              width: 90.0,
                              height: 47.0,
                              child: GeneratedAdsWidget(),
                            ),
                            Positioned(
                              left: 17.0,
                              top: 169.0,
                              right: null,
                              bottom: null,
                              width: 84.0,
                              height: 26.0,
                              child: GeneratedEmployeeWidget(),
                            ),
                            Positioned(
                              left: 133.0,
                              top: 169.0,
                              right: null,
                              bottom: null,
                              width: 73.0,
                              height: 26.0,
                              child: GeneratedServicesWidget(),
                            ),
                            Positioned(
                              left: 242.0,
                              top: 169.0,
                              right: null,
                              bottom: null,
                              width: 59.0,
                              height: 26.0,
                              child: GeneratedOrdersWidget(),
                            )
                          ]),
                    ))
              ])),
        );
      }),
    ));
  }
}
