import 'package:flutter/material.dart';
import 'package:flutterapp/hotelapp/bookingpagewidget/generated/GeneratedRectangle40Widget1.dart';
import 'package:flutterapp/hotelapp/bookingpagewidget/generated/GeneratedCompanysnameWidget.dart';
import 'package:flutterapp/hotelapp/bookingpagewidget/generated/GeneratedGroup70Widget.dart';
import 'package:flutterapp/hotelapp/bookingpagewidget/generated/GeneratedRectangle23Widget1.dart';
import 'package:flutterapp/hotelapp/bookingpagewidget/generated/GeneratedAdsWidget2.dart';
import 'package:flutterapp/hotelapp/bookingpagewidget/generated/GeneratedRectangle37Widget1.dart';
import 'package:flutterapp/hotelapp/bookingpagewidget/generated/GeneratedCompanyImageWidget.dart';
import 'package:flutterapp/hotelapp/bookingpagewidget/generated/GeneratedGroup76Widget.dart';
import 'package:flutterapp/hotelapp/bookingpagewidget/generated/GeneratedRectangle35Widget1.dart';
import 'package:flutterapp/hotelapp/bookingpagewidget/generated/GeneratedCompanyslocationWidget.dart';
import 'package:flutterapp/hotelapp/bookingpagewidget/generated/GeneratedRectangle33Widget.dart';

/* Frame Booking page
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedBookingpageWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: LayoutBuilder(
          builder: (BuildContext context, BoxConstraints constraints) {
        return SingleChildScrollView(
          scrollDirection: Axis.vertical,
          child: Container(
              height: 926.0,
              child: Stack(children: [
                Container(
                    width: constraints.maxWidth,
                    child: Container(
                      width: 428.0,
                      height: 926.0,
                      child: Stack(
                          fit: StackFit.expand,
                          alignment: Alignment.center,
                          overflow: Overflow.visible,
                          children: [
                            ClipRRect(
                              borderRadius: BorderRadius.zero,
                              child: Container(
                                color: Color.fromARGB(255, 255, 255, 255),
                              ),
                            ),
                            Positioned(
                              left: 0.0,
                              top: 0.0,
                              right: null,
                              bottom: null,
                              width: 428.0,
                              height: 842.0,
                              child: GeneratedRectangle33Widget(),
                            ),
                            Positioned(
                              left: 11.0,
                              top: 365.0,
                              right: null,
                              bottom: null,
                              width: 102.0,
                              height: 93.0,
                              child: GeneratedRectangle40Widget1(),
                            ),
                            Positioned(
                              left: 0.0,
                              top: 220.0,
                              right: null,
                              bottom: null,
                              width: 428.0,
                              height: 123.0,
                              child: GeneratedRectangle37Widget1(),
                            ),
                            Positioned(
                              left: 0.0,
                              top: 220.0,
                              right: null,
                              bottom: null,
                              width: 428.0,
                              height: 123.0,
                              child: GeneratedRectangle35Widget1(),
                            ),
                            Positioned(
                              left: 129.0,
                              top: 258.0,
                              right: null,
                              bottom: null,
                              width: 125.0,
                              height: 18.0,
                              child: GeneratedCompanyslocationWidget(),
                            ),
                            Positioned(
                              left: 129.0,
                              top: 235.0,
                              right: null,
                              bottom: null,
                              width: 110.0,
                              height: 18.0,
                              child: GeneratedCompanysnameWidget(),
                            ),
                            Positioned(
                              left: 11.0,
                              top: 235.0,
                              right: null,
                              bottom: null,
                              width: 102.0,
                              height: 93.0,
                              child: GeneratedRectangle23Widget1(),
                            ),
                            Positioned(
                              left: 11.0,
                              top: 274.0,
                              right: null,
                              bottom: null,
                              width: 104.0,
                              height: 18.0,
                              child: GeneratedCompanyImageWidget(),
                            ),
                            Positioned(
                              left: 0.0,
                              top: 0.0,
                              right: null,
                              bottom: null,
                              width: 428.0,
                              height: 208.0,
                              child: GeneratedAdsWidget2(),
                            ),
                            Positioned(
                              left: 306.0,
                              top: 228.0,
                              right: null,
                              bottom: null,
                              width: 112.0,
                              height: 46.0,
                              child: GeneratedGroup70Widget(),
                            ),
                            Positioned(
                              left: 11.0,
                              top: 865.0,
                              right: null,
                              bottom: null,
                              width: 59.0,
                              height: 55.0,
                              child: GeneratedGroup76Widget(),
                            )
                          ]),
                    ))
              ])),
        );
      }),
    ));
  }
}
