import 'package:flutter/material.dart';
import 'package:flutterapp/hotelapp/generatedorderswidget1/generated/GeneratedRectangle37Widget2.dart';
import 'package:flutterapp/hotelapp/generatedorderswidget1/generated/GeneratedAdsWidget3.dart';
import 'package:flutterapp/hotelapp/generatedorderswidget1/generated/GeneratedOrdersNameWidget1.dart';
import 'package:flutterapp/hotelapp/generatedorderswidget1/generated/GeneratedArrow3Widget1.dart';
import 'package:flutterapp/hotelapp/generatedorderswidget1/generated/GeneratedStatusWidget4.dart';
import 'package:flutterapp/hotelapp/generatedorderswidget1/generated/GeneratedHotelsNameWidget.dart';
import 'package:flutterapp/hotelapp/generatedorderswidget1/generated/GeneratedHotelsNameWidget3.dart';
import 'package:flutterapp/hotelapp/generatedorderswidget1/generated/GeneratedRectangle38Widget1.dart';
import 'package:flutterapp/hotelapp/generatedorderswidget1/generated/GeneratedRectangle39Widget1.dart';
import 'package:flutterapp/hotelapp/generatedorderswidget1/generated/GeneratedOrdersNameWidget.dart';
import 'package:flutterapp/hotelapp/generatedorderswidget1/generated/GeneratedGroup58Widget1.dart';
import 'package:flutterapp/hotelapp/generatedorderswidget1/generated/GeneratedCompanysNameWidget2.dart';
import 'package:flutterapp/hotelapp/generatedorderswidget1/generated/GeneratedHotelsNameWidget1.dart';
import 'package:flutterapp/hotelapp/generatedorderswidget1/generated/GeneratedGroup56Widget1.dart';
import 'package:flutterapp/hotelapp/generatedorderswidget1/generated/GeneratedOrdersNameWidget3.dart';
import 'package:flutterapp/hotelapp/generatedorderswidget1/generated/GeneratedRectangle22Widget5.dart';
import 'package:flutterapp/hotelapp/generatedorderswidget1/generated/GeneratedHotelsNameWidget2.dart';
import 'package:flutterapp/hotelapp/generatedorderswidget1/generated/GeneratedGroup59Widget1.dart';
import 'package:flutterapp/hotelapp/generatedorderswidget1/generated/GeneratedStatusWidget5.dart';
import 'package:flutterapp/hotelapp/generatedorderswidget1/generated/GeneratedCompanysNameWidget.dart';
import 'package:flutterapp/hotelapp/generatedorderswidget1/generated/GeneratedCompanysNameWidget3.dart';
import 'package:flutterapp/hotelapp/generatedorderswidget1/generated/GeneratedCompanysNameWidget1.dart';
import 'package:flutterapp/hotelapp/generatedorderswidget1/generated/GeneratedStatusWidget7.dart';
import 'package:flutterapp/hotelapp/generatedorderswidget1/generated/GeneratedEllipse14Widget1.dart';
import 'package:flutterapp/hotelapp/generatedorderswidget1/generated/GeneratedOrdersNameWidget2.dart';
import 'package:flutterapp/hotelapp/generatedorderswidget1/generated/GeneratedStatusWidget6.dart';
import 'package:flutterapp/hotelapp/generatedorderswidget1/generated/GeneratedRectangle40Widget2.dart';
import 'package:flutterapp/hotelapp/generatedorderswidget1/generated/GeneratedRectangle9Widget3.dart';
import 'package:flutterapp/hotelapp/generatedorderswidget1/generated/GeneratedGroup57Widget1.dart';

/* Frame Orders
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedOrdersWidget1 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: LayoutBuilder(
          builder: (BuildContext context, BoxConstraints constraints) {
        return SingleChildScrollView(
          scrollDirection: Axis.vertical,
          child: Container(
              height: 926.0,
              child: Stack(children: [
                Container(
                    width: constraints.maxWidth,
                    child: Container(
                      width: 428.0,
                      height: 926.0,
                      child: Stack(
                          fit: StackFit.expand,
                          alignment: Alignment.center,
                          overflow: Overflow.visible,
                          children: [
                            ClipRRect(
                              borderRadius: BorderRadius.zero,
                              child: Container(
                                color: Color.fromARGB(255, 255, 255, 255),
                              ),
                            ),
                            Positioned(
                              left: 1.0,
                              top: 254.0,
                              right: null,
                              bottom: null,
                              width: 428.0,
                              height: 123.0,
                              child: GeneratedRectangle37Widget2(),
                            ),
                            Positioned(
                              left: -1.0,
                              top: 401.0,
                              right: null,
                              bottom: null,
                              width: 428.0,
                              height: 123.0,
                              child: GeneratedRectangle38Widget1(),
                            ),
                            Positioned(
                              left: 0.0,
                              top: 548.0,
                              right: null,
                              bottom: null,
                              width: 428.0,
                              height: 123.0,
                              child: GeneratedRectangle39Widget1(),
                            ),
                            Positioned(
                              left: 0.0,
                              top: 695.0,
                              right: null,
                              bottom: null,
                              width: 428.0,
                              height: 123.0,
                              child: GeneratedRectangle40Widget2(),
                            ),
                            Positioned(
                              left: 18.0,
                              top: 265.0,
                              right: null,
                              bottom: null,
                              width: 91.0,
                              height: 18.0,
                              child: GeneratedOrdersNameWidget(),
                            ),
                            Positioned(
                              left: 16.0,
                              top: 412.0,
                              right: null,
                              bottom: null,
                              width: 91.0,
                              height: 18.0,
                              child: GeneratedOrdersNameWidget1(),
                            ),
                            Positioned(
                              left: 17.0,
                              top: 559.0,
                              right: null,
                              bottom: null,
                              width: 91.0,
                              height: 18.0,
                              child: GeneratedOrdersNameWidget2(),
                            ),
                            Positioned(
                              left: 17.0,
                              top: 706.0,
                              right: null,
                              bottom: null,
                              width: 91.0,
                              height: 18.0,
                              child: GeneratedOrdersNameWidget3(),
                            ),
                            Positioned(
                              left: 18.0,
                              top: 290.0,
                              right: null,
                              bottom: null,
                              width: 90.0,
                              height: 18.0,
                              child: GeneratedHotelsNameWidget(),
                            ),
                            Positioned(
                              left: 16.0,
                              top: 437.0,
                              right: null,
                              bottom: null,
                              width: 90.0,
                              height: 18.0,
                              child: GeneratedHotelsNameWidget1(),
                            ),
                            Positioned(
                              left: 17.0,
                              top: 584.0,
                              right: null,
                              bottom: null,
                              width: 90.0,
                              height: 18.0,
                              child: GeneratedHotelsNameWidget2(),
                            ),
                            Positioned(
                              left: 17.0,
                              top: 731.0,
                              right: null,
                              bottom: null,
                              width: 90.0,
                              height: 18.0,
                              child: GeneratedHotelsNameWidget3(),
                            ),
                            Positioned(
                              left: 18.0,
                              top: 345.0,
                              right: null,
                              bottom: null,
                              width: 46.0,
                              height: 21.0,
                              child: GeneratedStatusWidget4(),
                            ),
                            Positioned(
                              left: 16.0,
                              top: 492.0,
                              right: null,
                              bottom: null,
                              width: 46.0,
                              height: 21.0,
                              child: GeneratedStatusWidget5(),
                            ),
                            Positioned(
                              left: 17.0,
                              top: 639.0,
                              right: null,
                              bottom: null,
                              width: 46.0,
                              height: 21.0,
                              child: GeneratedStatusWidget6(),
                            ),
                            Positioned(
                              left: 17.0,
                              top: 786.0,
                              right: null,
                              bottom: null,
                              width: 46.0,
                              height: 21.0,
                              child: GeneratedStatusWidget7(),
                            ),
                            Positioned(
                              left: 18.0,
                              top: 318.0,
                              right: null,
                              bottom: null,
                              width: 115.0,
                              height: 18.0,
                              child: GeneratedCompanysNameWidget(),
                            ),
                            Positioned(
                              left: 16.0,
                              top: 465.0,
                              right: null,
                              bottom: null,
                              width: 115.0,
                              height: 18.0,
                              child: GeneratedCompanysNameWidget1(),
                            ),
                            Positioned(
                              left: 17.0,
                              top: 612.0,
                              right: null,
                              bottom: null,
                              width: 115.0,
                              height: 18.0,
                              child: GeneratedCompanysNameWidget2(),
                            ),
                            Positioned(
                              left: 17.0,
                              top: 759.0,
                              right: null,
                              bottom: null,
                              width: 115.0,
                              height: 18.0,
                              child: GeneratedCompanysNameWidget3(),
                            ),
                            Positioned(
                              left: -1.0,
                              top: 82.0,
                              right: null,
                              bottom: null,
                              width: 428.0,
                              height: 123.0,
                              child: GeneratedRectangle22Widget5(),
                            ),
                            Positioned(
                              left: 0.0,
                              top: -20.0,
                              right: null,
                              bottom: null,
                              width: 428.0,
                              height: 178.0,
                              child: GeneratedRectangle9Widget3(),
                            ),
                            Positioned(
                              left: 191.0,
                              top: 69.0,
                              right: null,
                              bottom: null,
                              width: 51.0,
                              height: 33.0,
                              child: GeneratedAdsWidget3(),
                            ),
                            Positioned(
                              left: 307.0,
                              top: 293.0,
                              right: null,
                              bottom: null,
                              width: 112.0,
                              height: 46.0,
                              child: GeneratedGroup56Widget1(),
                            ),
                            Positioned(
                              left: 305.0,
                              top: 440.0,
                              right: null,
                              bottom: null,
                              width: 112.0,
                              height: 46.0,
                              child: GeneratedGroup57Widget1(),
                            ),
                            Positioned(
                              left: 306.0,
                              top: 587.0,
                              right: null,
                              bottom: null,
                              width: 112.0,
                              height: 46.0,
                              child: GeneratedGroup58Widget1(),
                            ),
                            Positioned(
                              left: 306.0,
                              top: 734.0,
                              right: null,
                              bottom: null,
                              width: 112.0,
                              height: 46.0,
                              child: GeneratedGroup59Widget1(),
                            ),
                            Positioned(
                              left: 11.0,
                              top: 865.0,
                              right: null,
                              bottom: null,
                              width: 59.0,
                              height: 55.0,
                              child: GeneratedEllipse14Widget1(),
                            ),
                            Positioned(
                              left: 60.0,
                              top: 893.0,
                              right: null,
                              bottom: null,
                              width: 40.000003814697266,
                              height: 0.0,
                              child: GeneratedArrow3Widget1(),
                            )
                          ]),
                    ))
              ])),
        );
      }),
    ));
  }
}
