import 'package:flutter/material.dart';
import 'package:flutterapp/hotelapp/generatedcompanyprofilewidget/generated/GeneratedGroup5Widget.dart';
import 'package:flutterapp/hotelapp/generatedcompanyprofilewidget/generated/GeneratedRectangle15Widget1.dart';
import 'package:flutterapp/hotelapp/generatedcompanyprofilewidget/generated/GeneratedRectangle17Widget1.dart';
import 'package:flutterapp/hotelapp/generatedcompanyprofilewidget/generated/GeneratedRectangle16Widget1.dart';
import 'package:flutterapp/hotelapp/generatedcompanyprofilewidget/generated/GeneratedRectangle20Widget1.dart';
import 'package:flutterapp/hotelapp/generatedcompanyprofilewidget/generated/GeneratedRectangle18Widget1.dart';
import 'package:flutterapp/hotelapp/generatedcompanyprofilewidget/generated/GeneratedGroup4Widget2.dart';
import 'package:flutterapp/hotelapp/generatedcompanyprofilewidget/generated/GeneratedGroup3Widget.dart';
import 'package:flutterapp/hotelapp/generatedcompanyprofilewidget/generated/GeneratedRectangle14Widget1.dart';
import 'package:flutterapp/hotelapp/generatedcompanyprofilewidget/generated/GeneratedCompanyProfileWidget1.dart';
import 'package:flutterapp/hotelapp/generatedcompanyprofilewidget/generated/GeneratedGroup2Widget1.dart';
import 'package:flutterapp/hotelapp/generatedcompanyprofilewidget/generated/GeneratedBackgroundWidget1.dart';
import 'package:flutterapp/hotelapp/generatedcompanyprofilewidget/generated/GeneratedRectangle13Widget.dart';
import 'package:flutterapp/hotelapp/generatedcompanyprofilewidget/generated/GeneratedRectangle21Widget.dart';
import 'package:flutterapp/hotelapp/generatedcompanyprofilewidget/generated/GeneratedRectangle19Widget1.dart';

/* Frame Company Profile
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedCompanyProfileWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: LayoutBuilder(
          builder: (BuildContext context, BoxConstraints constraints) {
        return SingleChildScrollView(
          scrollDirection: Axis.vertical,
          child: Container(
              height: 926.0,
              child: Stack(children: [
                Container(
                    width: constraints.maxWidth,
                    child: Container(
                      width: 428.0,
                      height: 926.0,
                      child: Stack(
                          fit: StackFit.expand,
                          alignment: Alignment.center,
                          overflow: Overflow.visible,
                          children: [
                            ClipRRect(
                              borderRadius: BorderRadius.zero,
                              child: Container(
                                color: Color.fromARGB(255, 255, 255, 255),
                              ),
                            ),
                            Positioned(
                              left: 0.0,
                              top: 0.0,
                              right: null,
                              bottom: null,
                              width: 428.0,
                              height: 177.0,
                              child: GeneratedRectangle13Widget(),
                            ),
                            Positioned(
                              left: 319.0,
                              top: 10.0,
                              right: null,
                              bottom: null,
                              width: 100.0,
                              height: 26.0,
                              child: GeneratedBackgroundWidget1(),
                            ),
                            Positioned(
                              left: 16.0,
                              top: 21.0,
                              right: null,
                              bottom: null,
                              width: 111.0,
                              height: 101.0,
                              child: GeneratedGroup3Widget(),
                            ),
                            Positioned(
                              left: 0.0,
                              top: 137.0,
                              right: null,
                              bottom: null,
                              width: 428.0,
                              height: 650.0,
                              child: GeneratedRectangle14Widget1(),
                            ),
                            Positioned(
                              left: 46.0,
                              top: 202.0,
                              right: null,
                              bottom: null,
                              width: 335.0,
                              height: 49.0,
                              child: GeneratedRectangle15Widget1(),
                            ),
                            Positioned(
                              left: 46.0,
                              top: 287.0,
                              right: null,
                              bottom: null,
                              width: 335.0,
                              height: 49.0,
                              child: GeneratedRectangle16Widget1(),
                            ),
                            Positioned(
                              left: 46.0,
                              top: 372.0,
                              right: null,
                              bottom: null,
                              width: 335.0,
                              height: 49.0,
                              child: GeneratedRectangle17Widget1(),
                            ),
                            Positioned(
                              left: 46.0,
                              top: 457.0,
                              right: null,
                              bottom: null,
                              width: 335.0,
                              height: 49.0,
                              child: GeneratedRectangle18Widget1(),
                            ),
                            Positioned(
                              left: 46.0,
                              top: 542.0,
                              right: null,
                              bottom: null,
                              width: 335.0,
                              height: 49.0,
                              child: GeneratedRectangle19Widget1(),
                            ),
                            Positioned(
                              left: 46.0,
                              top: 627.0,
                              right: null,
                              bottom: null,
                              width: 335.0,
                              height: 49.0,
                              child: GeneratedRectangle20Widget1(),
                            ),
                            Positioned(
                              left: 46.0,
                              top: 712.0,
                              right: null,
                              bottom: null,
                              width: 335.0,
                              height: 49.0,
                              child: GeneratedRectangle21Widget(),
                            ),
                            Positioned(
                              left: 141.0,
                              top: 56.0,
                              right: null,
                              bottom: null,
                              width: 271.0,
                              height: 44.0,
                              child: GeneratedCompanyProfileWidget1(),
                            ),
                            Positioned(
                              left: 13.0,
                              top: 813.0,
                              right: null,
                              bottom: null,
                              width: 187.0,
                              height: 36.0,
                              child: GeneratedGroup2Widget1(),
                            ),
                            Positioned(
                              left: 224.0,
                              top: 813.0,
                              right: null,
                              bottom: null,
                              width: 187.0,
                              height: 36.0,
                              child: GeneratedGroup4Widget2(),
                            ),
                            Positioned(
                              left: 114.0,
                              top: 875.0,
                              right: null,
                              bottom: null,
                              width: 187.0,
                              height: 36.0,
                              child: GeneratedGroup5Widget(),
                            )
                          ]),
                    ))
              ])),
        );
      }),
    ));
  }
}
