import 'package:flutter/material.dart';
import 'package:flutterapp/hotelapp/generatedforgotpasswordwidget/generated/GeneratedGroup92Widget1.dart';
import 'package:flutterapp/hotelapp/generatedforgotpasswordwidget/generated/GeneratedPhoneNumberWidget.dart';
import 'package:flutterapp/hotelapp/generatedforgotpasswordwidget/generated/GeneratedRectangle6Widget1.dart';
import 'package:flutterapp/hotelapp/generatedforgotpasswordwidget/generated/GeneratedGroup1Widget.dart';

/* Frame Forgot Password
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedForgotPasswordWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: LayoutBuilder(
          builder: (BuildContext context, BoxConstraints constraints) {
        return SingleChildScrollView(
          scrollDirection: Axis.vertical,
          child: Container(
              height: 926.0,
              child: Stack(children: [
                Container(
                    width: constraints.maxWidth,
                    child: Container(
                      width: 428.0,
                      height: 926.0,
                      child: Stack(
                          fit: StackFit.expand,
                          alignment: Alignment.center,
                          overflow: Overflow.visible,
                          children: [
                            ClipRRect(
                              borderRadius: BorderRadius.zero,
                              child: Container(
                                color: Color.fromARGB(255, 255, 255, 255),
                              ),
                            ),
                            Positioned(
                              left: 32.0,
                              top: 282.0,
                              right: null,
                              bottom: null,
                              width: 365.0,
                              height: 38.0,
                              child: GeneratedRectangle6Widget1(),
                            ),
                            Positioned(
                              left: 44.0,
                              top: 290.0,
                              right: null,
                              bottom: null,
                              width: 136.0,
                              height: 25.0,
                              child: GeneratedPhoneNumberWidget(),
                            ),
                            Positioned(
                              left: 87.0,
                              top: 347.0,
                              right: null,
                              bottom: null,
                              width: 234.0,
                              height: 36.0,
                              child: GeneratedGroup1Widget(),
                            ),
                            Positioned(
                              left: 101.0,
                              top: 50.0,
                              right: null,
                              bottom: null,
                              width: 227.0,
                              height: 181.0,
                              child: GeneratedGroup92Widget1(),
                            )
                          ]),
                    ))
              ])),
        );
      }),
    ));
  }
}
