import 'package:flutter/material.dart';
import 'package:flutterapp/hotelapp/generatediphone13promax1widget/generated/GeneratedOTPWidget.dart';
import 'package:flutterapp/hotelapp/generatediphone13promax1widget/generated/GeneratedRectangle6Widget2.dart';
import 'package:flutterapp/hotelapp/generatediphone13promax1widget/generated/GeneratedNewpasswordWidget.dart';
import 'package:flutterapp/hotelapp/generatediphone13promax1widget/generated/GeneratedRectangle5Widget.dart';
import 'package:flutterapp/hotelapp/generatediphone13promax1widget/generated/GeneratedGroup92Widget2.dart';
import 'package:flutterapp/hotelapp/generatediphone13promax1widget/generated/GeneratedUpdateWidget.dart';
import 'package:flutterapp/hotelapp/generatediphone13promax1widget/generated/GeneratedRectangle7Widget2.dart';

/* Frame iPhone 13 Pro Max - 1
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedIPhone13ProMax1Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: LayoutBuilder(
          builder: (BuildContext context, BoxConstraints constraints) {
        return SingleChildScrollView(
          scrollDirection: Axis.vertical,
          child: Container(
              height: 926.0,
              child: Stack(children: [
                Container(
                    width: constraints.maxWidth,
                    child: Container(
                      width: 428.0,
                      height: 926.0,
                      child: Stack(
                          fit: StackFit.expand,
                          alignment: Alignment.center,
                          overflow: Overflow.visible,
                          children: [
                            ClipRRect(
                              borderRadius: BorderRadius.zero,
                              child: Container(
                                color: Color.fromARGB(255, 255, 255, 255),
                              ),
                            ),
                            Positioned(
                              left: 32.0,
                              top: 322.0,
                              right: null,
                              bottom: null,
                              width: 365.0,
                              height: 38.0,
                              child: GeneratedRectangle5Widget(),
                            ),
                            Positioned(
                              left: 59.0,
                              top: 330.0,
                              right: null,
                              bottom: null,
                              width: 134.0,
                              height: 25.0,
                              child: GeneratedNewpasswordWidget(),
                            ),
                            Positioned(
                              left: 32.0,
                              top: 268.0,
                              right: null,
                              bottom: null,
                              width: 365.0,
                              height: 38.0,
                              child: GeneratedRectangle6Widget2(),
                            ),
                            Positioned(
                              left: 59.0,
                              top: 277.0,
                              right: null,
                              bottom: null,
                              width: 44.0,
                              height: 28.0,
                              child: GeneratedOTPWidget(),
                            ),
                            Positioned(
                              left: 94.0,
                              top: 387.0,
                              right: null,
                              bottom: null,
                              width: 234.0,
                              height: 36.0,
                              child: GeneratedRectangle7Widget2(),
                            ),
                            Positioned(
                              left: 163.0,
                              top: 391.0,
                              right: null,
                              bottom: null,
                              width: 85.0,
                              height: 30.0,
                              child: GeneratedUpdateWidget(),
                            ),
                            Positioned(
                              left: 98.0,
                              top: 51.0,
                              right: null,
                              bottom: null,
                              width: 227.0,
                              height: 181.0,
                              child: GeneratedGroup92Widget2(),
                            )
                          ]),
                    ))
              ])),
        );
      }),
    ));
  }
}
