import 'package:flutter/material.dart';
import 'package:flutterapp/hotelapp/generatedserviceswidget1/generated/GeneratedComanysNameWidget5.dart';
import 'package:flutterapp/hotelapp/generatedserviceswidget1/generated/GeneratedAdsWidget4.dart';
import 'package:flutterapp/hotelapp/generatedserviceswidget1/generated/GeneratedRectangle42Widget1.dart';
import 'package:flutterapp/hotelapp/generatedserviceswidget1/generated/GeneratedRectangle35Widget2.dart';
import 'package:flutterapp/hotelapp/generatedserviceswidget1/generated/GeneratedRectangle40Widget3.dart';
import 'package:flutterapp/hotelapp/generatedserviceswidget1/generated/GeneratedRectangle39Widget2.dart';
import 'package:flutterapp/hotelapp/generatedserviceswidget1/generated/GeneratedServicesNameWidget3.dart';
import 'package:flutterapp/hotelapp/generatedserviceswidget1/generated/GeneratedComanysNameWidget6.dart';
import 'package:flutterapp/hotelapp/generatedserviceswidget1/generated/GeneratedPriceWidget.dart';
import 'package:flutterapp/hotelapp/generatedserviceswidget1/generated/GeneratedPriceWidget1.dart';
import 'package:flutterapp/hotelapp/generatedserviceswidget1/generated/GeneratedEllipse14Widget2.dart';
import 'package:flutterapp/hotelapp/generatedserviceswidget1/generated/GeneratedRectangle22Widget6.dart';
import 'package:flutterapp/hotelapp/generatedserviceswidget1/generated/GeneratedGroup58Widget2.dart';
import 'package:flutterapp/hotelapp/generatedserviceswidget1/generated/GeneratedRectangle43Widget1.dart';
import 'package:flutterapp/hotelapp/generatedserviceswidget1/generated/GeneratedComanysNameWidget4.dart';
import 'package:flutterapp/hotelapp/generatedserviceswidget1/generated/GeneratedServicesNameWidget2.dart';
import 'package:flutterapp/hotelapp/generatedserviceswidget1/generated/GeneratedRectangle9Widget4.dart';
import 'package:flutterapp/hotelapp/generatedserviceswidget1/generated/GeneratedGroup57Widget2.dart';
import 'package:flutterapp/hotelapp/generatedserviceswidget1/generated/GeneratedArrow3Widget2.dart';
import 'package:flutterapp/hotelapp/generatedserviceswidget1/generated/GeneratedGroup59Widget2.dart';
import 'package:flutterapp/hotelapp/generatedserviceswidget1/generated/GeneratedServicesNameWidget1.dart';
import 'package:flutterapp/hotelapp/generatedserviceswidget1/generated/GeneratedPriceWidget3.dart';
import 'package:flutterapp/hotelapp/generatedserviceswidget1/generated/GeneratedRectangle41Widget1.dart';
import 'package:flutterapp/hotelapp/generatedserviceswidget1/generated/GeneratedComanysNameWidget7.dart';
import 'package:flutterapp/hotelapp/generatedserviceswidget1/generated/GeneratedGroup56Widget2.dart';
import 'package:flutterapp/hotelapp/generatedserviceswidget1/generated/GeneratedPriceWidget2.dart';
import 'package:flutterapp/hotelapp/generatedserviceswidget1/generated/GeneratedRectangle38Widget2.dart';
import 'package:flutterapp/hotelapp/generatedserviceswidget1/generated/GeneratedServicesNameWidget.dart';
import 'package:flutterapp/hotelapp/generatedserviceswidget1/generated/GeneratedRectangle37Widget3.dart';

/* Frame Services
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedServicesWidget1 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: LayoutBuilder(
          builder: (BuildContext context, BoxConstraints constraints) {
        return SingleChildScrollView(
          scrollDirection: Axis.vertical,
          child: Container(
              height: 926.0,
              child: Stack(children: [
                Container(
                    width: constraints.maxWidth,
                    child: Container(
                      width: 428.0,
                      height: 926.0,
                      child: Stack(
                          fit: StackFit.expand,
                          alignment: Alignment.center,
                          overflow: Overflow.visible,
                          children: [
                            ClipRRect(
                              borderRadius: BorderRadius.zero,
                              child: Container(
                                color: Color.fromARGB(255, 255, 255, 255),
                              ),
                            ),
                            Positioned(
                              left: 0.0,
                              top: 228.0,
                              right: null,
                              bottom: null,
                              width: 428.0,
                              height: 123.0,
                              child: GeneratedRectangle37Widget3(),
                            ),
                            Positioned(
                              left: 0.0,
                              top: 391.0,
                              right: null,
                              bottom: null,
                              width: 428.0,
                              height: 123.0,
                              child: GeneratedRectangle38Widget2(),
                            ),
                            Positioned(
                              left: -1.0,
                              top: 554.0,
                              right: null,
                              bottom: null,
                              width: 428.0,
                              height: 123.0,
                              child: GeneratedRectangle40Widget3(),
                            ),
                            Positioned(
                              left: -1.0,
                              top: 717.0,
                              right: null,
                              bottom: null,
                              width: 428.0,
                              height: 123.0,
                              child: GeneratedRectangle42Widget1(),
                            ),
                            Positioned(
                              left: 0.0,
                              top: 228.0,
                              right: null,
                              bottom: null,
                              width: 428.0,
                              height: 123.0,
                              child: GeneratedRectangle35Widget2(),
                            ),
                            Positioned(
                              left: 0.0,
                              top: 391.0,
                              right: null,
                              bottom: null,
                              width: 428.0,
                              height: 123.0,
                              child: GeneratedRectangle39Widget2(),
                            ),
                            Positioned(
                              left: -1.0,
                              top: 554.0,
                              right: null,
                              bottom: null,
                              width: 428.0,
                              height: 123.0,
                              child: GeneratedRectangle41Widget1(),
                            ),
                            Positioned(
                              left: -1.0,
                              top: 717.0,
                              right: null,
                              bottom: null,
                              width: 428.0,
                              height: 123.0,
                              child: GeneratedRectangle43Widget1(),
                            ),
                            Positioned(
                              left: 22.0,
                              top: 282.0,
                              right: null,
                              bottom: null,
                              width: 102.0,
                              height: 18.0,
                              child: GeneratedServicesNameWidget(),
                            ),
                            Positioned(
                              left: 22.0,
                              top: 445.0,
                              right: null,
                              bottom: null,
                              width: 102.0,
                              height: 18.0,
                              child: GeneratedServicesNameWidget1(),
                            ),
                            Positioned(
                              left: 21.0,
                              top: 608.0,
                              right: null,
                              bottom: null,
                              width: 102.0,
                              height: 18.0,
                              child: GeneratedServicesNameWidget2(),
                            ),
                            Positioned(
                              left: 21.0,
                              top: 771.0,
                              right: null,
                              bottom: null,
                              width: 102.0,
                              height: 18.0,
                              child: GeneratedServicesNameWidget3(),
                            ),
                            Positioned(
                              left: 22.0,
                              top: 319.0,
                              right: null,
                              bottom: null,
                              width: 37.0,
                              height: 21.0,
                              child: GeneratedPriceWidget(),
                            ),
                            Positioned(
                              left: 22.0,
                              top: 482.0,
                              right: null,
                              bottom: null,
                              width: 37.0,
                              height: 21.0,
                              child: GeneratedPriceWidget1(),
                            ),
                            Positioned(
                              left: 21.0,
                              top: 645.0,
                              right: null,
                              bottom: null,
                              width: 37.0,
                              height: 21.0,
                              child: GeneratedPriceWidget2(),
                            ),
                            Positioned(
                              left: 21.0,
                              top: 808.0,
                              right: null,
                              bottom: null,
                              width: 37.0,
                              height: 21.0,
                              child: GeneratedPriceWidget3(),
                            ),
                            Positioned(
                              left: 22.0,
                              top: 245.0,
                              right: null,
                              bottom: null,
                              width: 108.0,
                              height: 18.0,
                              child: GeneratedComanysNameWidget4(),
                            ),
                            Positioned(
                              left: 22.0,
                              top: 408.0,
                              right: null,
                              bottom: null,
                              width: 108.0,
                              height: 18.0,
                              child: GeneratedComanysNameWidget5(),
                            ),
                            Positioned(
                              left: 21.0,
                              top: 571.0,
                              right: null,
                              bottom: null,
                              width: 108.0,
                              height: 18.0,
                              child: GeneratedComanysNameWidget6(),
                            ),
                            Positioned(
                              left: 21.0,
                              top: 734.0,
                              right: null,
                              bottom: null,
                              width: 108.0,
                              height: 18.0,
                              child: GeneratedComanysNameWidget7(),
                            ),
                            Positioned(
                              left: -1.0,
                              top: 82.0,
                              right: null,
                              bottom: null,
                              width: 428.0,
                              height: 123.0,
                              child: GeneratedRectangle22Widget6(),
                            ),
                            Positioned(
                              left: 0.0,
                              top: -20.0,
                              right: null,
                              bottom: null,
                              width: 428.0,
                              height: 178.0,
                              child: GeneratedRectangle9Widget4(),
                            ),
                            Positioned(
                              left: 191.0,
                              top: 69.0,
                              right: null,
                              bottom: null,
                              width: 51.0,
                              height: 33.0,
                              child: GeneratedAdsWidget4(),
                            ),
                            Positioned(
                              left: 306.0,
                              top: 267.0,
                              right: null,
                              bottom: null,
                              width: 112.0,
                              height: 46.0,
                              child: GeneratedGroup56Widget2(),
                            ),
                            Positioned(
                              left: 306.0,
                              top: 430.0,
                              right: null,
                              bottom: null,
                              width: 112.0,
                              height: 46.0,
                              child: GeneratedGroup57Widget2(),
                            ),
                            Positioned(
                              left: 305.0,
                              top: 593.0,
                              right: null,
                              bottom: null,
                              width: 112.0,
                              height: 46.0,
                              child: GeneratedGroup58Widget2(),
                            ),
                            Positioned(
                              left: 305.0,
                              top: 756.0,
                              right: null,
                              bottom: null,
                              width: 112.0,
                              height: 46.0,
                              child: GeneratedGroup59Widget2(),
                            ),
                            Positioned(
                              left: 11.0,
                              top: 865.0,
                              right: null,
                              bottom: null,
                              width: 59.0,
                              height: 55.0,
                              child: GeneratedEllipse14Widget2(),
                            ),
                            Positioned(
                              left: 60.0,
                              top: 893.0,
                              right: null,
                              bottom: null,
                              width: 40.000003814697266,
                              height: 0.0,
                              child: GeneratedArrow3Widget2(),
                            )
                          ]),
                    ))
              ])),
        );
      }),
    ));
  }
}
