import 'package:flutter/material.dart';
import 'package:flutterapp/hotelapp/generatedemployeesdetailwidget/generated/GeneratedRectangle16Widget2.dart';
import 'package:flutterapp/hotelapp/generatedemployeesdetailwidget/generated/GeneratedRectangle15Widget2.dart';
import 'package:flutterapp/hotelapp/generatedemployeesdetailwidget/generated/GeneratedRectangle22Widget1.dart';
import 'package:flutterapp/hotelapp/generatedemployeesdetailwidget/generated/GeneratedRectangle18Widget2.dart';
import 'package:flutterapp/hotelapp/generatedemployeesdetailwidget/generated/GeneratedGroup3Widget1.dart';
import 'package:flutterapp/hotelapp/generatedemployeesdetailwidget/generated/GeneratedRectangle21Widget1.dart';
import 'package:flutterapp/hotelapp/generatedemployeesdetailwidget/generated/GeneratedRectangle20Widget2.dart';
import 'package:flutterapp/hotelapp/generatedemployeesdetailwidget/generated/GeneratedGroup4Widget3.dart';
import 'package:flutterapp/hotelapp/generatedemployeesdetailwidget/generated/GeneratedRectangle19Widget2.dart';
import 'package:flutterapp/hotelapp/generatedemployeesdetailwidget/generated/GeneratedGroup2Widget2.dart';
import 'package:flutterapp/hotelapp/generatedemployeesdetailwidget/generated/GeneratedEmployeeProfileWidget.dart';
import 'package:flutterapp/hotelapp/generatedemployeesdetailwidget/generated/GeneratedBackgroundWidget2.dart';
import 'package:flutterapp/hotelapp/generatedemployeesdetailwidget/generated/GeneratedRectangle13Widget1.dart';
import 'package:flutterapp/hotelapp/generatedemployeesdetailwidget/generated/GeneratedRectangle14Widget2.dart';
import 'package:flutterapp/hotelapp/generatedemployeesdetailwidget/generated/GeneratedRectangle17Widget2.dart';

/* Frame Employee 's Detail
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedEmployeesDetailWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: LayoutBuilder(
          builder: (BuildContext context, BoxConstraints constraints) {
        return SingleChildScrollView(
          scrollDirection: Axis.vertical,
          child: Container(
              height: 926.0,
              child: Stack(children: [
                Container(
                    width: constraints.maxWidth,
                    child: Container(
                      width: 428.0,
                      height: 926.0,
                      child: Stack(
                          fit: StackFit.expand,
                          alignment: Alignment.center,
                          overflow: Overflow.visible,
                          children: [
                            ClipRRect(
                              borderRadius: BorderRadius.zero,
                              child: Container(
                                color: Color.fromARGB(255, 255, 255, 255),
                              ),
                            ),
                            Positioned(
                              left: 0.0,
                              top: 0.0,
                              right: null,
                              bottom: null,
                              width: 428.0,
                              height: 177.0,
                              child: GeneratedRectangle13Widget1(),
                            ),
                            Positioned(
                              left: 319.0,
                              top: 10.0,
                              right: null,
                              bottom: null,
                              width: 100.0,
                              height: 26.0,
                              child: GeneratedBackgroundWidget2(),
                            ),
                            Positioned(
                              left: 16.0,
                              top: 21.0,
                              right: null,
                              bottom: null,
                              width: 111.0,
                              height: 101.0,
                              child: GeneratedGroup3Widget1(),
                            ),
                            Positioned(
                              left: 0.0,
                              top: 137.0,
                              right: null,
                              bottom: null,
                              width: 428.0,
                              height: 726.0,
                              child: GeneratedRectangle14Widget2(),
                            ),
                            Positioned(
                              left: 46.0,
                              top: 202.0,
                              right: null,
                              bottom: null,
                              width: 335.0,
                              height: 49.0,
                              child: GeneratedRectangle15Widget2(),
                            ),
                            Positioned(
                              left: 46.0,
                              top: 287.0,
                              right: null,
                              bottom: null,
                              width: 335.0,
                              height: 49.0,
                              child: GeneratedRectangle16Widget2(),
                            ),
                            Positioned(
                              left: 46.0,
                              top: 372.0,
                              right: null,
                              bottom: null,
                              width: 335.0,
                              height: 49.0,
                              child: GeneratedRectangle17Widget2(),
                            ),
                            Positioned(
                              left: 46.0,
                              top: 457.0,
                              right: null,
                              bottom: null,
                              width: 335.0,
                              height: 49.0,
                              child: GeneratedRectangle18Widget2(),
                            ),
                            Positioned(
                              left: 46.0,
                              top: 542.0,
                              right: null,
                              bottom: null,
                              width: 335.0,
                              height: 49.0,
                              child: GeneratedRectangle19Widget2(),
                            ),
                            Positioned(
                              left: 46.0,
                              top: 627.0,
                              right: null,
                              bottom: null,
                              width: 335.0,
                              height: 49.0,
                              child: GeneratedRectangle20Widget2(),
                            ),
                            Positioned(
                              left: 46.0,
                              top: 712.0,
                              right: null,
                              bottom: null,
                              width: 335.0,
                              height: 49.0,
                              child: GeneratedRectangle21Widget1(),
                            ),
                            Positioned(
                              left: 46.0,
                              top: 786.0,
                              right: null,
                              bottom: null,
                              width: 335.0,
                              height: 49.0,
                              child: GeneratedRectangle22Widget1(),
                            ),
                            Positioned(
                              left: 138.0,
                              top: 56.0,
                              right: null,
                              bottom: null,
                              width: 277.0,
                              height: 44.0,
                              child: GeneratedEmployeeProfileWidget(),
                            ),
                            Positioned(
                              left: 13.0,
                              top: 878.0,
                              right: null,
                              bottom: null,
                              width: 187.0,
                              height: 36.0,
                              child: GeneratedGroup2Widget2(),
                            ),
                            Positioned(
                              left: 224.0,
                              top: 878.0,
                              right: null,
                              bottom: null,
                              width: 187.0,
                              height: 36.0,
                              child: GeneratedGroup4Widget3(),
                            )
                          ]),
                    ))
              ])),
        );
      }),
    ));
  }
}
