import 'package:flutter/material.dart';
import 'package:flutterapp/hotelapp/generatedemployeewidget1/generated/GeneratedComanysNameWidget2.dart';
import 'package:flutterapp/hotelapp/generatedemployeewidget1/generated/GeneratedRectangle9Widget2.dart';
import 'package:flutterapp/hotelapp/generatedemployeewidget1/generated/GeneratedPhoneWidget3.dart';
import 'package:flutterapp/hotelapp/generatedemployeewidget1/generated/GeneratedStatusWidget.dart';
import 'package:flutterapp/hotelapp/generatedemployeewidget1/generated/GeneratedPhoneWidget1.dart';
import 'package:flutterapp/hotelapp/generatedemployeewidget1/generated/GeneratedAdsWidget1.dart';
import 'package:flutterapp/hotelapp/generatedemployeewidget1/generated/GeneratedNameWidget3.dart';
import 'package:flutterapp/hotelapp/generatedemployeewidget1/generated/GeneratedRectangle43Widget.dart';
import 'package:flutterapp/hotelapp/generatedemployeewidget1/generated/GeneratedGroup61Widget.dart';
import 'package:flutterapp/hotelapp/generatedemployeewidget1/generated/GeneratedStatusWidget2.dart';
import 'package:flutterapp/hotelapp/generatedemployeewidget1/generated/GeneratedGroup3Widget3.dart';
import 'package:flutterapp/hotelapp/generatedemployeewidget1/generated/GeneratedGroup58Widget.dart';
import 'package:flutterapp/hotelapp/generatedemployeewidget1/generated/GeneratedRectangle39Widget.dart';
import 'package:flutterapp/hotelapp/generatedemployeewidget1/generated/GeneratedRectangle35Widget.dart';
import 'package:flutterapp/hotelapp/generatedemployeewidget1/generated/GeneratedNameWidget4.dart';
import 'package:flutterapp/hotelapp/generatedemployeewidget1/generated/GeneratedRectangle37Widget.dart';
import 'package:flutterapp/hotelapp/generatedemployeewidget1/generated/GeneratedRectangle42Widget.dart';
import 'package:flutterapp/hotelapp/generatedemployeewidget1/generated/GeneratedStatusWidget1.dart';
import 'package:flutterapp/hotelapp/generatedemployeewidget1/generated/GeneratedRectangle38Widget.dart';
import 'package:flutterapp/hotelapp/generatedemployeewidget1/generated/GeneratedRectangle40Widget.dart';
import 'package:flutterapp/hotelapp/generatedemployeewidget1/generated/GeneratedPhoneWidget2.dart';
import 'package:flutterapp/hotelapp/generatedemployeewidget1/generated/GeneratedComanysNameWidget1.dart';
import 'package:flutterapp/hotelapp/generatedemployeewidget1/generated/GeneratedRectangle22Widget4.dart';
import 'package:flutterapp/hotelapp/generatedemployeewidget1/generated/GeneratedPhoneWidget.dart';
import 'package:flutterapp/hotelapp/generatedemployeewidget1/generated/GeneratedArrow3Widget.dart';
import 'package:flutterapp/hotelapp/generatedemployeewidget1/generated/GeneratedGroup57Widget.dart';
import 'package:flutterapp/hotelapp/generatedemployeewidget1/generated/GeneratedEllipse14Widget.dart';
import 'package:flutterapp/hotelapp/generatedemployeewidget1/generated/GeneratedGroup60Widget.dart';
import 'package:flutterapp/hotelapp/generatedemployeewidget1/generated/GeneratedStatusWidget3.dart';
import 'package:flutterapp/hotelapp/generatedemployeewidget1/generated/GeneratedGroup56Widget.dart';
import 'package:flutterapp/hotelapp/generatedemployeewidget1/generated/GeneratedRectangle41Widget.dart';
import 'package:flutterapp/hotelapp/generatedemployeewidget1/generated/GeneratedComanysNameWidget3.dart';
import 'package:flutterapp/hotelapp/generatedemployeewidget1/generated/GeneratedNameWidget1.dart';
import 'package:flutterapp/hotelapp/generatedemployeewidget1/generated/GeneratedComanysNameWidget.dart';
import 'package:flutterapp/hotelapp/generatedemployeewidget1/generated/GeneratedGroup59Widget.dart';
import 'package:flutterapp/hotelapp/generatedemployeewidget1/generated/GeneratedNameWidget2.dart';
import 'package:flutterapp/hotelapp/generatedemployeewidget1/generated/GeneratedGroup62Widget.dart';

/* Frame Employee
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedEmployeeWidget1 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: LayoutBuilder(
          builder: (BuildContext context, BoxConstraints constraints) {
        return SingleChildScrollView(
          scrollDirection: Axis.vertical,
          child: Container(
              height: 926.0,
              child: Stack(children: [
                Container(
                    width: constraints.maxWidth,
                    child: Container(
                      width: 428.0,
                      height: 926.0,
                      child: Stack(
                          fit: StackFit.expand,
                          alignment: Alignment.center,
                          overflow: Overflow.visible,
                          children: [
                            ClipRRect(
                              borderRadius: BorderRadius.zero,
                              child: Container(
                                color: Color.fromARGB(255, 255, 255, 255),
                              ),
                            ),
                            Positioned(
                              left: 1.0,
                              top: 254.0,
                              right: null,
                              bottom: null,
                              width: 428.0,
                              height: 123.0,
                              child: GeneratedRectangle37Widget(),
                            ),
                            Positioned(
                              left: 0.0,
                              top: 400.0,
                              right: null,
                              bottom: null,
                              width: 428.0,
                              height: 123.0,
                              child: GeneratedRectangle38Widget(),
                            ),
                            Positioned(
                              left: 0.0,
                              top: 546.0,
                              right: null,
                              bottom: null,
                              width: 428.0,
                              height: 123.0,
                              child: GeneratedRectangle40Widget(),
                            ),
                            Positioned(
                              left: 0.0,
                              top: 692.0,
                              right: null,
                              bottom: null,
                              width: 428.0,
                              height: 123.0,
                              child: GeneratedRectangle42Widget(),
                            ),
                            Positioned(
                              left: 1.0,
                              top: 254.0,
                              right: null,
                              bottom: null,
                              width: 428.0,
                              height: 123.0,
                              child: GeneratedRectangle35Widget(),
                            ),
                            Positioned(
                              left: 0.0,
                              top: 400.0,
                              right: null,
                              bottom: null,
                              width: 428.0,
                              height: 123.0,
                              child: GeneratedRectangle39Widget(),
                            ),
                            Positioned(
                              left: 0.0,
                              top: 546.0,
                              right: null,
                              bottom: null,
                              width: 428.0,
                              height: 123.0,
                              child: GeneratedRectangle41Widget(),
                            ),
                            Positioned(
                              left: 0.0,
                              top: 692.0,
                              right: null,
                              bottom: null,
                              width: 428.0,
                              height: 123.0,
                              child: GeneratedRectangle43Widget(),
                            ),
                            Positioned(
                              left: 130.0,
                              top: 292.0,
                              right: null,
                              bottom: null,
                              width: 43.0,
                              height: 21.0,
                              child: GeneratedNameWidget1(),
                            ),
                            Positioned(
                              left: 129.0,
                              top: 438.0,
                              right: null,
                              bottom: null,
                              width: 43.0,
                              height: 21.0,
                              child: GeneratedNameWidget2(),
                            ),
                            Positioned(
                              left: 129.0,
                              top: 584.0,
                              right: null,
                              bottom: null,
                              width: 43.0,
                              height: 21.0,
                              child: GeneratedNameWidget3(),
                            ),
                            Positioned(
                              left: 129.0,
                              top: 730.0,
                              right: null,
                              bottom: null,
                              width: 43.0,
                              height: 21.0,
                              child: GeneratedNameWidget4(),
                            ),
                            Positioned(
                              left: 130.0,
                              top: 319.0,
                              right: null,
                              bottom: null,
                              width: 45.0,
                              height: 21.0,
                              child: GeneratedPhoneWidget(),
                            ),
                            Positioned(
                              left: 129.0,
                              top: 465.0,
                              right: null,
                              bottom: null,
                              width: 45.0,
                              height: 21.0,
                              child: GeneratedPhoneWidget1(),
                            ),
                            Positioned(
                              left: 129.0,
                              top: 611.0,
                              right: null,
                              bottom: null,
                              width: 45.0,
                              height: 21.0,
                              child: GeneratedPhoneWidget2(),
                            ),
                            Positioned(
                              left: 129.0,
                              top: 757.0,
                              right: null,
                              bottom: null,
                              width: 45.0,
                              height: 21.0,
                              child: GeneratedPhoneWidget3(),
                            ),
                            Positioned(
                              left: 130.0,
                              top: 347.0,
                              right: null,
                              bottom: null,
                              width: 46.0,
                              height: 21.0,
                              child: GeneratedStatusWidget(),
                            ),
                            Positioned(
                              left: 129.0,
                              top: 493.0,
                              right: null,
                              bottom: null,
                              width: 46.0,
                              height: 21.0,
                              child: GeneratedStatusWidget1(),
                            ),
                            Positioned(
                              left: 129.0,
                              top: 639.0,
                              right: null,
                              bottom: null,
                              width: 46.0,
                              height: 21.0,
                              child: GeneratedStatusWidget2(),
                            ),
                            Positioned(
                              left: 129.0,
                              top: 785.0,
                              right: null,
                              bottom: null,
                              width: 46.0,
                              height: 21.0,
                              child: GeneratedStatusWidget3(),
                            ),
                            Positioned(
                              left: 130.0,
                              top: 269.0,
                              right: null,
                              bottom: null,
                              width: 108.0,
                              height: 18.0,
                              child: GeneratedComanysNameWidget(),
                            ),
                            Positioned(
                              left: 129.0,
                              top: 415.0,
                              right: null,
                              bottom: null,
                              width: 108.0,
                              height: 18.0,
                              child: GeneratedComanysNameWidget1(),
                            ),
                            Positioned(
                              left: 129.0,
                              top: 561.0,
                              right: null,
                              bottom: null,
                              width: 108.0,
                              height: 18.0,
                              child: GeneratedComanysNameWidget2(),
                            ),
                            Positioned(
                              left: 129.0,
                              top: 707.0,
                              right: null,
                              bottom: null,
                              width: 108.0,
                              height: 18.0,
                              child: GeneratedComanysNameWidget3(),
                            ),
                            Positioned(
                              left: -1.0,
                              top: 82.0,
                              right: null,
                              bottom: null,
                              width: 428.0,
                              height: 123.0,
                              child: GeneratedRectangle22Widget4(),
                            ),
                            Positioned(
                              left: 0.0,
                              top: -20.0,
                              right: null,
                              bottom: null,
                              width: 428.0,
                              height: 178.0,
                              child: GeneratedRectangle9Widget2(),
                            ),
                            Positioned(
                              left: 191.0,
                              top: 69.0,
                              right: null,
                              bottom: null,
                              width: 51.0,
                              height: 33.0,
                              child: GeneratedAdsWidget1(),
                            ),
                            Positioned(
                              left: 307.0,
                              top: 293.0,
                              right: null,
                              bottom: null,
                              width: 112.0,
                              height: 46.0,
                              child: GeneratedGroup56Widget(),
                            ),
                            Positioned(
                              left: 306.0,
                              top: 439.0,
                              right: null,
                              bottom: null,
                              width: 112.0,
                              height: 46.0,
                              child: GeneratedGroup57Widget(),
                            ),
                            Positioned(
                              left: 306.0,
                              top: 585.0,
                              right: null,
                              bottom: null,
                              width: 112.0,
                              height: 46.0,
                              child: GeneratedGroup59Widget(),
                            ),
                            Positioned(
                              left: 306.0,
                              top: 731.0,
                              right: null,
                              bottom: null,
                              width: 112.0,
                              height: 46.0,
                              child: GeneratedGroup61Widget(),
                            ),
                            Positioned(
                              left: 11.0,
                              top: 865.0,
                              right: null,
                              bottom: null,
                              width: 59.0,
                              height: 55.0,
                              child: GeneratedEllipse14Widget(),
                            ),
                            Positioned(
                              left: 60.0,
                              top: 893.0,
                              right: null,
                              bottom: null,
                              width: 40.000003814697266,
                              height: 0.0,
                              child: GeneratedArrow3Widget(),
                            ),
                            Positioned(
                              left: 9.0,
                              top: 262.0,
                              right: null,
                              bottom: null,
                              width: 111.0,
                              height: 101.0,
                              child: GeneratedGroup3Widget3(),
                            ),
                            Positioned(
                              left: 8.0,
                              top: 408.0,
                              right: null,
                              bottom: null,
                              width: 111.0,
                              height: 101.0,
                              child: GeneratedGroup58Widget(),
                            ),
                            Positioned(
                              left: 8.0,
                              top: 554.0,
                              right: null,
                              bottom: null,
                              width: 111.0,
                              height: 101.0,
                              child: GeneratedGroup60Widget(),
                            ),
                            Positioned(
                              left: 8.0,
                              top: 700.0,
                              right: null,
                              bottom: null,
                              width: 111.0,
                              height: 101.0,
                              child: GeneratedGroup62Widget(),
                            )
                          ]),
                    ))
              ])),
        );
      }),
    ));
  }
}
